# Generated by Django 4.2.1 on 2023-05-30 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("team_app", "0003_alter_teammodel_users"),
        ("user_app", "0003_alter_usermodel_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskModel",
            fields=[
                ("task_id", models.AutoField(primary_key=True, serialize=False)),
                ("task_title", models.CharField(max_length=64)),
                ("task_description", models.CharField(max_length=128)),
                (
                    "task_status",
                    models.CharField(
                        choices=[
                            ("OPEN", "OPEN"),
                            ("IN_PROGRESS", "IN_PROGRESS"),
                            ("COMPLETE", "COMPLETE"),
                        ],
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                ("creation_time", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user_app.usermodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProjectBoardModel",
            fields=[
                ("board_id", models.AutoField(primary_key=True, serialize=False)),
                ("board_name", models.CharField(max_length=64, unique=True)),
                ("description", models.CharField(max_length=128)),
                (
                    "board_status",
                    models.CharField(
                        choices=[("OPEN", "OPEN"), ("CLOSED", "CLOSED")],
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                ("completion_time", models.DateTimeField(blank=True)),
                ("creation_time", models.DateTimeField(auto_now_add=True)),
                (
                    "tasks",
                    models.ManyToManyField(
                        default=None,
                        related_name="tasks",
                        to="project_board_app.taskmodel",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="team_app.teammodel",
                    ),
                ),
            ],
        ),
    ]
