# Generated by Django 4.2.1 on 2023-05-30 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("team_app", "0003_alter_teammodel_users"),
        ("project_board_app", "0002_alter_projectboardmodel_completion_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskmodel",
            name="team",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="team_app.teammodel",
            ),
        ),
    ]
