# Generated by Django 4.2.1 on 2023-05-30 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user_app", "0003_alter_usermodel_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamModel",
            fields=[
                ("team_id", models.AutoField(primary_key=True, serialize=False)),
                ("team_name", models.CharField(max_length=64, unique=True)),
                ("description", models.CharField(blank=True, max_length=128)),
                ("creation_time", models.DateTimeField(auto_now_add=True)),
                (
                    "admin",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user_app.usermodel",
                    ),
                ),
                (
                    "users",
                    models.ManyToManyField(
                        related_name="users", to="user_app.usermodel"
                    ),
                ),
            ],
        ),
    ]
