# Generated by Django 4.2.1 on 2023-05-30 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0003_alter_usermodel_description_and_more"),
        ("team_app", "0002_alter_teammodel_admin_alter_teammodel_users"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teammodel",
            name="users",
            field=models.ManyToManyField(related_name="users", to="user_app.usermodel"),
        ),
    ]
