# Generated by Django 4.2.1 on 2023-05-29 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserModel",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("user_name", models.CharField(max_length=64, unique=True)),
                ("display_name", models.CharField(max_length=64)),
                ("description", models.CharField(max_length=128)),
                ("creation_time", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
