# Generated by Django 4.2.1 on 2023-05-29 22:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0002_alter_usermodel_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermodel",
            name="description",
            field=models.CharField(
                blank=True,
                max_length=128,
                validators=[django.core.validators.MaxLengthValidator(128)],
            ),
        ),
        migrations.AlterField(
            model_name="usermodel",
            name="display_name",
            field=models.CharField(
                max_length=64,
                validators=[django.core.validators.MaxLengthValidator(64)],
            ),
        ),
        migrations.AlterField(
            model_name="usermodel",
            name="user_name",
            field=models.CharField(
                max_length=64,
                unique=True,
                validators=[django.core.validators.MaxLengthValidator(64)],
            ),
        ),
    ]
